// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxFKvLuHejC012GYaiQqMM5jzLFJPl1U',
    appId: '1:434506431986:ios:5ce4ce5181bd164901ff6b',
    messagingSenderId: '434506431986',
    projectId: 'flutterauthapp-f54b4',
    storageBucket: 'flutterauthapp-f54b4.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKm_KEw27V16-skapIpCAfiQigFuhdgPI',
    appId: '1:434506431986:web:18260b2365bbe81001ff6b',
    messagingSenderId: '434506431986',
    projectId: 'flutterauthapp-f54b4',
    authDomain: 'flutterauthapp-f54b4.firebaseapp.com',
    storageBucket: 'flutterauthapp-f54b4.appspot.com',
    measurementId: 'G-E8FCHFR5H7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxFKvLuHejC012GYaiQqMM5jzLFJPl1U',
    appId: '1:434506431986:ios:5ce4ce5181bd164901ff6b',
    messagingSenderId: '434506431986',
    projectId: 'flutterauthapp-f54b4',
    storageBucket: 'flutterauthapp-f54b4.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAip5BPogwJxS8Jhk5bv4gIh6MRaPw3cdI',
    appId: '1:434506431986:android:a610922d906c204901ff6b',
    messagingSenderId: '434506431986',
    projectId: 'flutterauthapp-f54b4',
    storageBucket: 'flutterauthapp-f54b4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKm_KEw27V16-skapIpCAfiQigFuhdgPI',
    appId: '1:434506431986:web:0cd2f358dca20bf801ff6b',
    messagingSenderId: '434506431986',
    projectId: 'flutterauthapp-f54b4',
    authDomain: 'flutterauthapp-f54b4.firebaseapp.com',
    storageBucket: 'flutterauthapp-f54b4.appspot.com',
    measurementId: 'G-R65C025LF5',
  );

}